name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install AdoptOpenJDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: "11"
    - name: Run tests
      run: sbt test
